### ISSUE TITLE
Fix all yaml files where syntax is broken

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#1016]
Symfony Yaml 2.8.0 has deprecated this syntax.

```yaml
some_service:
    class: ...
    arguments:
        - @whatever
``` 

because a scalar cannot be started by the reserved `@` indicator.
We must fix all files to that, with simple quotes:

```yaml
some_service:
    class: ...
    arguments:
        - '@whatever'
```
