### ISSUE TITLE
Error trying to use only EntityTranslatorBundle

### ISSUE THREAD

**Issue by almacbe** [elcodi/elcodi#426]
I am trying to use entity translator bundle but the service "elcodi.core.entity_translator.services.cached_entity_translation_provider" doesn't found the service "doctrine_cache.providers.elcodi". Maybe some dependency missed?

**Comment by mmoreram** [comment]
Okay, to make it happen what you have to do is update the eventListener definition, so you can override the `locales`, that is an array of locale isos, and `master_locale`, that is the iso of the master locale.

``` yml
    elcodi.core.entity_translator.event_listener.entity_translator_form:
        class: %elcodi.core.entity_translator.event_listener.entity_translator_form.class%
        arguments:
            translation_provider: @elcodi.entity_translation_provider
            configuration: %elcodi.core.entity_translator.configuration%
            locales: @elcodi.languages_iso_array
            master_locale: %elcodi.core.entity_translator.language_master_locale%
            fallback: %elcodi.core.entity_translator.language_fallback%
            changes_bag: @elcodi.entity_translator_changes
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: saveEntityTranslations }
```

Finally, for the cache, you need to inject a `DoctrineCache` instance in the setter call.

``` yml
    elcodi.core.entity_translator.services.cached_entity_translation_provider:
        class: %elcodi.core.entity_translator.services.cached_entity_translation_provider.class%
        arguments:
            translation_provider: @elcodi.core.entity_translator.services.entity_translation_provider
            translation_repository: @elcodi.repository.entity_translation
            cache_prefix: %elcodi.core.entity_translator.cache_prefix%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_translations]]
        tags:
            - { name: kernel.event_listener, event: translator.warmup, method: warmUp }
```

Instead of `@doctrine_cache.providers.elcodi_translations`, you can inject your own cache instance.
