### ISSUE TITLE
Refactor CartCoupon service names according to new naming

### ISSUE THREAD

**Issue by alch** [elcodi/elcodi#795]
`CartCoupon` Component and Bundle naming in classes and services has not yet been changed according to the new naming policy.

It looks like it only affects `eventListener` definitions.

```
AutomaticCouponApplicatorListener
AvoidDuplicatesListener
CartCouponManagerListener
CheckCartCouponListener
CheckCouponListener
CheckRulesListener
ConvertToOrderCouponsListener
MinimumPriceCouponListener
OrderCouponManagerListener
RefreshCouponsListener
StackableCouponListener
```

The **Listener** part of the file and class name should be renamed **EventListener**.

Same for event listener service definition:

```
    elcodi.event_listener.cart_coupon.refresh_coupons:
    elcodi.event_listener.cart_coupon.automatic_coupons:
    elcodi.event_listener.cart_coupon.avoid_coupon_duplicates:
    elcodi.event_listener.cart_coupon.stackable_coupon:
    elcodi.event_listener.cart_coupon.cart_coupon_checker:
    elcodi.event_listener.cart_coupon.cart_coupon_manager:
    elcodi.event_listener.cart_coupon.coupon_checker:
    elcodi.event_listener.cart_coupon.check_minimum_price:
    elcodi.event_listener.cart_coupon.check_rules:
    elcodi.event_listener.cart_coupon.convert_to_order:
    elcodi.event_listener.cart_coupon.order_coupon_manager:
```

Where short naming should be used, like `elcodi.event_listener.stackable_coupon`
