### ISSUE TITLE
Splitting documentations and prevent maintainance

### ISSUE THREAD

**Issue by EmanueleMinotto** [elcodi/elcodi#942]
Documentations (coverage & docs) are currently included only in elcodi/elcodi and related repositories like elcodi/User don't contain any of them.

I would suggest another strategy to prevent thier maintainance and a not required inclusion inside the source branch while keeping them updated with the source code:
![strategy](http://www.websequencediagrams.com/cgi-bin/cdraw?lz=TG9jYWxob3N0LT5HaXRIdWI6IGdpdCBwdXNoCgALBi0-Z2l0c3BsaXQ6IAACBXRpbmcgc3ViZGlyZWN0b3JpZXMKABsIACsbVHJhdmlzLUNJOiBwb3N0LXB1c2ggaG9vawoAEQkAGA1hZnRlcl9zY3JpcHQgAAEGAB4MAIEmCABCBWRvY3MgaW50byBnaC1wYWdlcwo&s=mscgen)

The required lines in `.travis.yml` are:

```yaml
php:
- 5.6

env:
  global:
    secure: *travis secure key*

after_script:
- if [ $TRAVIS_PHP_VERSION = '5.6' ]; then sh generate-doc.sh; fi
```

and in the *generate-doc.sh* file the only required variable (extracted from env) is `${GH_TOKEN}`.
